In [1]:
import numpy as np

In [2]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [3]:
print("x3 ndim: ", x3.ndim) #the number of dims
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [4]:
print("dtype: ", x3.dtype)

dtype:  int64


In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbyptes:", x3.nbytes, "bytes") #nbytes = itemsize * size

itemsize: 8 bytes
nbyptes: 480 bytes


In [6]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
x = np.array([1,2,3])

In [8]:
x.reshape((1,3))

array([[1, 2, 3]])